import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { TopicTag } from "@/components/shared/topic-tag";
import { formatTimestamp } from "./video-player";
import { Clock, Sparkles } from "lucide-react";
import type { KeyPoint } from "@/types";

interface VideoSummaryProps {
  summary: string | null;
  keyPoints: KeyPoint[] | null;
  topics: string[] | null;
}

export function VideoSummary({ summary, keyPoints, topics }: VideoSummaryProps) {
  if (!summary) {
    return (
      <Card>
        <CardContent className="py-8 text-center text-muted-foreground">
          No summary available yet. This video is still being processed.
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" />
            AI-Generated Summary
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm leading-relaxed">{summary}</p>
          {topics && topics.length > 0 && (
            <div className="flex flex-wrap gap-1.5 mt-4">
              {topics.map((topic) => (
                <TopicTag key={topic} topicId={topic} />
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {keyPoints && keyPoints.length > 0 && (
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base">Key Points</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-3">
              {keyPoints.map((point, i) => (
                <li key={i} className="flex gap-3 text-sm">
                  <Badge variant="outline" className="shrink-0 h-6 gap-1 font-mono text-xs">
                    <Clock className="h-3 w-3" />
                    {formatTimestamp(point.timestampSeconds)}
                  </Badge>
                  <span>{point.text}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      <p className="text-xs text-muted-foreground italic">
        This summary was generated by AI (Gemini) and may contain inaccuracies. Always refer to the
        original video for authoritative information.
      </p>
    </div>
  );
}
